@baseURL = http://localhost:3000/users
### 🔹 Listar todos os jogadores

GET {{baseURL}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFuYS5zb3V6YUBlbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NTEyNDE2MTksImV4cCI6MTc1MTI0NTIxOX0.QLLCqSw7bjLTGTys1Uhrl-69EGS4EBI1xwNKfCeVu1Q

### 🔸 Adicionar um novo usuario
POST {{baseURL}}
Content-Type: application/json

{
    "name": "Ana Souzaa",
    "email": "ana.souza@email.com",
    "phone": "11987654321",
    "role": "admin",
    "password": "teste"
}

### 🔹 Buscar usuário por ID (Substitua :id por um ID existente)
GET {{baseURL}}/1
Content-Type: application/json

### 🔹 Atualizar usuário por ID (Substitua :id por um ID existente)
PUT {{baseURL}}/1
Content-Type: application/json

{
    "name": "Ana Souzaa",
    "email": "ana.souza@email.com",
    "phone": "11987654321",
    "role": "admin"
}

### 🔹 Deletar usuário por ID (Substitua :id por um ID existente)

DELETE {{baseURL}}/1
Content-Type: application/json


### Login do novo usuário (pegar o token gerado abaixo)
POST {{baseURL}}/login
Content-Type: application/json

{
 "email": "ana.souza@email.com",
 "password": "teste"
}