@baseURL = http://localhost:3000/pets
### 🔹 Listar todos os jogadores

GET {{baseURL}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmEuc291emFAZW1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzMxMDU1LCJleHAiOjE3NTEzMzQ2NTV9.InsqETyNwUTVV3r3ynUdov2m1j1qXLoPYsNsxqHc7DY

### 🔹 Listar todos os jogadores disponiveis
GET {{baseURL}}/available
Content-Type: application/json

### 🔹 Buscar um jogo por ID
GET {{baseURL}}/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmEuc291emFAZW1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzMxMDU1LCJleHAiOjE3NTEzMzQ2NTV9.InsqETyNwUTVV3r3ynUdov2m1j1qXLoPYsNsxqHc7DY


### 🔸 Adicionar um novo pet
POST {{baseURL}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmEuc291emFAZW1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzMxMDU1LCJleHAiOjE3NTEzMzQ2NTV9.InsqETyNwUTVV3r3ynUdov2m1j1qXLoPYsNsxqHc7DY

{
  "name": "Miurso",
  "age": 2,
  "species": "Gato",
  "size": "small",
  "status": "available",
  "description": "Gato branco muito brincalhão."
}

### 🔸 Atualizar um pet existente (ID = 1)
PUT {{baseURL}}/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmEuc291emFAZW1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzMxMDU1LCJleHAiOjE3NTEzMzQ2NTV9.InsqETyNwUTVV3r3ynUdov2m1j1qXLoPYsNsxqHc7DY

{
  "name": "Thor",
  "age": 4,
  "species": "Cachorro",
  "size": "large",
  "status": "adopted",
  "description": "Cão grande, dócil e adotado recentemente."
}

### 🔸 Deletar um pet (ID = 1)
DELETE {{baseURL}}/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJhbmEuc291emFAZW1haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxMzMxMDU1LCJleHAiOjE3NTEzMzQ2NTV9.InsqETyNwUTVV3r3ynUdov2m1j1qXLoPYsNsxqHc7DY